CREATE TYPE media_type AS ENUM ('Image', 'Video', 'Audio', 'Book');
CREATE TYPE tag_type AS ENUM ('General', 'People');

CREATE TABLE "users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" character varying NOT NULL,
  "pass_hash" character varying NOT NULL,
  "is_admin" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");

CREATE TABLE "posts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "media_type" media_type NOT NULL,
  "filename" character varying NOT NULL,
  "file_ext" character varying NOT NULL,
  "user_owns" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "posts_users_owns" FOREIGN KEY ("user_owns") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX "posts_filename_key" ON "posts" ("filename");

CREATE TABLE "tags" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "tag_type" tag_type NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "tags_name_key" ON "tags" ("name");

CREATE TABLE "post_tags" (
  "post_id" bigint NOT NULL,
  "tag_id" bigint NOT NULL,
  PRIMARY KEY ("post_id", "tag_id"),
  CONSTRAINT "post_tags_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE,
  CONSTRAINT "post_tags_tag_id" FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON DELETE CASCADE
);

CREATE TABLE "sessions" (
  "id" character varying NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "sessions_users_sessions" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE TABLE "user_favourites" (
  "user_id" bigint NOT NULL,
  "post_id" bigint NOT NULL,
  PRIMARY KEY ("user_id", "post_id"),
  CONSTRAINT "user_favourites_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
  CONSTRAINT "user_favourites_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE
);

CREATE INDEX "idx_posttags_tag_id" ON "post_tags" ("tag_id");
CREATE INDEX "idx_posttags_post_id" ON "post_tags" ("post_id");

CREATE INDEX "idx_userfavourites_user_id" ON "user_favourites" ("user_id");
CREATE INDEX "idx_userfavourites_post_id" ON "user_favourites" ("post_id");